[versions]
dokka = "1.8.10"
kotlin = "1.8.10"
kotlinx-binary-compatibility-validator = "0.14.0"
kotlinx-serialization = "1.5.0"

# ---------------------------------- Plugins -----------------------------------

[plugins.dokka]
id = "org.jetbrains.dokka"
version.ref = "dokka"

[plugins.kotlin-multiplatform]
id = "org.jetbrains.kotlin.multiplatform"
version.ref = "kotlin"

[plugins.kotlinx-binary-compatibility-validator]
id = "org.jetbrains.kotlinx.binary-compatibility-validator"
version.ref = "kotlinx-binary-compatibility-validator"

[plugins.kotlinx-serialization]
id = "org.jetbrains.kotlin.plugin.serialization"
version.ref = "kotlin"

# --------------------------------- Libraries ----------------------------------

[libraries.dokka-base]
group = "org.jetbrains.dokka"
name = "dokka-base"
version.ref = "dokka"

[libraries.dokka-gradle-plugin]
group = "org.jetbrains.dokka"
name = "org.jetbrains.dokka.gradle.plugin"
version.ref = "dokka"

[libraries.dokka-versioning]
group = "org.jetbrains.dokka"
name = "versioning-plugin"
version.ref = "dokka"

[libraries.junit-jupiter]
group = "org.junit.jupiter"
name = "junit-jupiter"
version = "5.8.2"

[libraries.kotlin-bom]
group = "org.jetbrains.kotlin"
name = "kotlin-bom"
version.ref = "kotlin"

[libraries.kotlin-gradle-plugin]
group = "org.jetbrains.kotlin"
name = "kotlin-gradle-plugin"
version.ref = "kotlin"

[libraries.kotlin-test]
group = "org.jetbrains.kotlin"
name = "kotlin-test"
version.ref = "kotlin"

[libraries.kotlinx-serialization-core]
group = "org.jetbrains.kotlinx"
name = "kotlinx-serialization-core"
version.ref = "kotlinx-serialization"

[libraries.kotlinx-serialization-json]
group = "org.jetbrains.kotlinx"
name = "kotlinx-serialization-json"
version.ref = "kotlinx-serialization"
